-- 1. Create the project_attachments table
CREATE TABLE IF NOT EXISTS "public"."project_attachments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dubbing_project_id" bigint NOT NULL REFERENCES "public"."dubbing_projects"("id") ON DELETE CASCADE,
    "file_path" text NOT NULL,
    "file_name" text NOT NULL,
    "description" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "created_by" uuid DEFAULT auth.uid() REFERENCES "auth"."users"("id") ON DELETE SET NULL
);

ALTER TABLE "public"."project_attachments" OWNER TO "postgres";

-- 2. Enable RLS for the table
ALTER TABLE "public"."project_attachments" ENABLE ROW LEVEL SECURITY;

-- 3. Policies for project_attachments table (Editors/Admins only)
CREATE POLICY "Allow editors read access to project_attachments" ON "public"."project_attachments"
    FOR SELECT
    USING (
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );

CREATE POLICY "Allow editors insert access to project_attachments" ON "public"."project_attachments"
    FOR INSERT
    WITH CHECK (
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );

CREATE POLICY "Allow editors delete access to project_attachments" ON "public"."project_attachments"
    FOR DELETE
    USING (
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );

CREATE POLICY "Allow editors update access to project_attachments" ON "public"."project_attachments"
    FOR UPDATE
    USING (
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    )
    WITH CHECK (
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );

-- 4. Storage Bucket Policies for project_attachments bucket
-- Note: the bucket itself is created via config.toml, but we define the policies here.
INSERT INTO storage.buckets (id, name, public) VALUES ('project_attachments', 'project_attachments', false) ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Allow editors read access to project_attachments bucket" ON storage.objects
    FOR SELECT
    USING (
        bucket_id = 'project_attachments' AND
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );

CREATE POLICY "Allow editors insert access to project_attachments bucket" ON storage.objects
    FOR INSERT
    WITH CHECK (
        bucket_id = 'project_attachments' AND
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );

CREATE POLICY "Allow editors delete access to project_attachments bucket" ON storage.objects
    FOR DELETE
    USING (
        bucket_id = 'project_attachments' AND
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );
