-- 1. Create studios table
CREATE TABLE IF NOT EXISTS "public"."studios" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL UNIQUE,
    "description" text,
    "country" text,
    "city" text,
    "website_url" text,
    "logo_url" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."studios" OWNER TO "postgres";

-- 2. Enable RLS and add policies for studios
ALTER TABLE "public"."studios" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to studios" ON "public"."studios"
    FOR SELECT USING (true);

CREATE POLICY "Allow authenticated write access to studios" ON "public"."studios"
    FOR ALL
    USING (auth.role() = 'authenticated');

-- 3. Add studio_id column to dubbing_projects
ALTER TABLE "public"."dubbing_projects"
ADD COLUMN IF NOT EXISTS "studio_id" bigint REFERENCES "public"."studios"("id") ON DELETE SET NULL;

-- 4. Populate studios from existing distinct studio names in dubbing_projects
INSERT INTO "public"."studios" ("name")
SELECT DISTINCT "studio"
FROM "public"."dubbing_projects"
WHERE "studio" IS NOT NULL AND TRIM("studio") != ''
ON CONFLICT ("name") DO NOTHING;

-- 5. Update studio_id foreign key in dubbing_projects
UPDATE "public"."dubbing_projects" dp
SET "studio_id" = s.id
FROM "public"."studios" s
WHERE dp.studio = s.name AND dp.studio_id IS NULL;
