-- 1. Create the new dubbing_projects table
CREATE TABLE IF NOT EXISTS "public"."dubbing_projects" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "content_id" bigint NOT NULL,
    "content_type" text NOT NULL,
    "language" text DEFAULT 'fr'::text,
    "studio" text,
    "artistic_director" text,
    "adaptation" text,
    "recording" text,
    "editing" text,
    "mixing" text,
    "project_manager" text,
    "creative_supervision" text,
    "status" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."dubbing_projects" OWNER TO "postgres";

-- 2. Enable RLS and add basic policies
ALTER TABLE "public"."dubbing_projects" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON "public"."dubbing_projects"
    FOR SELECT
    USING (true);

CREATE POLICY "Allow authenticated insert access" ON "public"."dubbing_projects"
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow individual update access" ON "public"."dubbing_projects"
    FOR UPDATE
    USING (auth.role() = 'authenticated');

-- 3. Modify the existing work table to add dubbing_project_id
ALTER TABLE "public"."work"
ADD COLUMN "dubbing_project_id" bigint;

-- 4. Insert unique (content_id, content_type) into dubbing_projects
INSERT INTO "public"."dubbing_projects" ("content_id", "content_type")
SELECT DISTINCT "content_id", "content_type"
FROM "public"."work";

-- 5. Update work table to link to the new dubbing_project_id
UPDATE "public"."work" w
SET "dubbing_project_id" = dp.id
FROM "public"."dubbing_projects" dp
WHERE w.content_id = dp.content_id AND w.content_type = dp.content_type;

-- 6. Make the dubbing_project_id NOT NULL and add Foreign Key constraint with ON DELETE CASCADE
ALTER TABLE "public"."work"
ALTER COLUMN "dubbing_project_id" SET NOT NULL;

ALTER TABLE "public"."work"
ADD CONSTRAINT "work_dubbing_project_id_fkey" FOREIGN KEY ("dubbing_project_id") REFERENCES "public"."dubbing_projects"("id") ON DELETE CASCADE;