-- 1. Create the dubbing_project_crew table
CREATE TABLE IF NOT EXISTS "public"."dubbing_project_crew" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dubbing_project_id" bigint NOT NULL REFERENCES "public"."dubbing_projects"("id") ON DELETE CASCADE,
    "person_id" bigint NOT NULL REFERENCES "public"."voice_actors"("id") ON DELETE CASCADE,
    "job" text NOT NULL,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."dubbing_project_crew" OWNER TO "postgres";

-- 2. Enable RLS and add basic policies
ALTER TABLE "public"."dubbing_project_crew" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON "public"."dubbing_project_crew"
    FOR SELECT
    USING (true);

CREATE POLICY "Allow authenticated insert access" ON "public"."dubbing_project_crew"
    FOR INSERT
    WITH CHECK (
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );

CREATE POLICY "Allow individual update access" ON "public"."dubbing_project_crew"
    FOR UPDATE
    USING (
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );

CREATE POLICY "Allow individual delete access" ON "public"."dubbing_project_crew"
    FOR DELETE
    USING (
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin', 'editor') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin', 'editor') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin', 'editor')
        )
    );

-- 3. Drop the old text columns from dubbing_projects
ALTER TABLE "public"."dubbing_projects"
  DROP COLUMN IF EXISTS "artistic_director",
  DROP COLUMN IF EXISTS "adaptation",
  DROP COLUMN IF EXISTS "recording",
  DROP COLUMN IF EXISTS "editing",
  DROP COLUMN IF EXISTS "mixing",
  DROP COLUMN IF EXISTS "project_manager",
  DROP COLUMN IF EXISTS "creative_supervision";
