-- 1. Create the jobs table
CREATE TABLE IF NOT EXISTS "public"."jobs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL UNIQUE,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."jobs" OWNER TO "postgres";

-- 2. Insert default jobs
INSERT INTO "public"."jobs" ("name") VALUES 
  ('Direction Artistique'),
  ('Adaptation'),
  ('Enregistrement'),
  ('Montage'),
  ('Mixage'),
  ('Chargé de projet'),
  ('Creative Supervision');

-- 3. Enable RLS and add basic policies for jobs
ALTER TABLE "public"."jobs" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON "public"."jobs"
    FOR SELECT
    USING (true);

CREATE POLICY "Allow admin write access" ON "public"."jobs"
    FOR ALL
    USING (
        auth.role() = 'authenticated' AND
        (
            auth.jwt()->>'role' IN ('admin') OR
            (auth.jwt()->'user_metadata'->>'role') IN ('admin') OR
            (auth.jwt()->'app_metadata'->>'role') IN ('admin')
        )
    );

-- 4. Alter dubbing_project_crew to use job_id
-- We will clear the dubbing_project_crew table if it has data since we can't reliably map the old text fields 
-- (which were internal codes like 'artistic_director') to the new names dynamically without a CASE statement,
-- and it was just created today.
TRUNCATE TABLE "public"."dubbing_project_crew";

ALTER TABLE "public"."dubbing_project_crew" DROP COLUMN IF EXISTS "job";

ALTER TABLE "public"."dubbing_project_crew" 
ADD COLUMN "job_id" bigint NOT NULL REFERENCES "public"."jobs"("id") ON DELETE CASCADE;
