export default defineEventHandler(async (event) => {
  const user = event.context.user;
  if (!user) {
    throw createError({ statusCode: 401, message: "Unauthorized" });
  }

  const body = await readBody(event).catch(() => ({}));
  const { firstname, lastname, details, voice_actor_id } = body;

  if (!firstname || !lastname) {
    throw createError({
      statusCode: 400,
      message: "Missing required fields: firstname and lastname",
    });
  }

  const config = useRuntimeConfig();
  const resendApiKey = config.resendApiKey;
  if (!resendApiKey) {
    console.error("RESEND_API_KEY environment variable is not configured.");
    throw createError({
      statusCode: 500,
      message: "Email sending service is not configured on the server",
    });
  }

  const toEmail = config.resendToEmail || "onboarding@resend.dev";
  const fromEmail = config.resendFromEmail || "onboarding@resend.dev";

  const isLinkageRequest = !!voice_actor_id;
  const subject = isLinkageRequest
    ? `Voice Actor Linkage Request: ${firstname} ${lastname}`
    : `New Voice Actor Page Request: ${firstname} ${lastname}`;

  const htmlContent = `
    <div style="font-family: sans-serif; padding: 20px; color: #1e293b; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
      <h2 style="color: #2563eb; margin-top: 0; border-bottom: 2px solid #f1f5f9; padding-bottom: 10px;">${isLinkageRequest ? "Voice Actor Linkage Request" : "Voice Actor Page Request"}</h2>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
        <tr>
          <td style="padding: 8px 0; font-weight: bold; width: 150px; color: #64748b;">Requested By:</td>
          <td style="padding: 8px 0; color: #0f172a;">${user.email || "Unknown User"}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #64748b;">Actor Name:</td>
          <td style="padding: 8px 0; font-weight: bold; color: #0f172a;">${firstname} ${lastname}</td>
        </tr>
        ${
          isLinkageRequest
            ? `
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #64748b;">Voice Actor ID:</td>
          <td style="padding: 8px 0; font-weight: bold; color: #0f172a;">${voice_actor_id}</td>
        </tr>
        `
            : ""
        }
      </table>
      
      <div style="margin-top: 20px; background-color: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #f1f5f9;">
        <h4 style="margin-top: 0; margin-bottom: 8px; color: #475569;">Additional Request Details:</h4>
        <p style="margin: 0; white-space: pre-wrap; font-size: 14px; line-height: 1.5; color: #334155;">${details || "No additional details provided."}</p>
      </div>
      
      <p style="font-size: 12px; color: #94a3b8; margin-top: 30px; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 15px;">
        This email was automatically generated by DubbingBase.
      </p>
    </div>
  `;

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${resendApiKey}`,
    },
    body: JSON.stringify({
      from: fromEmail,
      to: toEmail,
      subject: subject,
      html: htmlContent,
    }),
  });

  if (!res.ok) {
    const errorText = await res.text();
    console.error("Resend API responded with error:", errorText);
    throw createError({
      statusCode: 502,
      message: "Failed to send request email via Resend",
    });
  }

  const resData = await res.json();
  return { success: true, emailId: resData.id };
});
