import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { Database } from "../_shared/database.types.ts";
import { createErrorResponse, createResponse } from "../_shared/http-utils.ts";
import { withSupabase } from "npm:@supabase/server@^1";

export default {
  fetch: withSupabase<Database>({ auth: "user" }, async (req, ctx) => {
    try {
      const user = ctx.userClaims;
      if (!user) {
        return Response.json({ error: "Unauthorized" }, { status: 401 });
      }

      const body = await req.json().catch(() => ({}));
      const { firstname, lastname, details } = body;

      if (!firstname || !lastname) {
        return createErrorResponse(
          "Missing required fields: firstname and lastname",
          400,
        );
      }

      const resendApiKey = Deno.env.get("RESEND_API_KEY");
      if (!resendApiKey) {
        console.error("RESEND_API_KEY environment variable is not configured.");
        return createErrorResponse(
          "Email sending service is not configured on the server",
          500,
        );
      }

      const toEmail =
        Deno.env.get("RESEND_TO_EMAIL") || "onboarding@resend.dev";
      const fromEmail =
        Deno.env.get("RESEND_FROM_EMAIL") || "onboarding@resend.dev";

      const subject = `New Voice Actor Page Request: ${firstname} ${lastname}`;
      const htmlContent = `
        <div style="font-family: sans-serif; padding: 20px; color: #1e293b; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
          <h2 style="color: #2563eb; margin-top: 0; border-bottom: 2px solid #f1f5f9; padding-bottom: 10px;">Voice Actor Page Request</h2>
          
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; width: 150px; color: #64748b;">Requested By:</td>
              <td style="padding: 8px 0; color: #0f172a;">${user.email || "Unknown User"}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #64748b;">Actor Name:</td>
              <td style="padding: 8px 0; font-weight: bold; color: #0f172a;">${firstname} ${lastname}</td>
            </tr>
          </table>
          
          <div style="margin-top: 20px; background-color: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #f1f5f9;">
            <h4 style="margin-top: 0; margin-bottom: 8px; color: #475569;">Additional Request Details:</h4>
            <p style="margin: 0; white-space: pre-wrap; font-size: 14px; line-height: 1.5; color: #334155;">${details || "No additional details provided."}</p>
          </div>
          
          <p style="font-size: 12px; color: #94a3b8; margin-top: 30px; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 15px;">
            This email was automatically generated by DubbingBase.
          </p>
        </div>
      `;

      console.log(
        `Sending voice actor request email for ${firstname} ${lastname} from ${fromEmail} to ${toEmail}`,
      );

      const res = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${resendApiKey}`,
        },
        body: JSON.stringify({
          from: fromEmail,
          to: toEmail,
          subject: subject,
          html: htmlContent,
        }),
      });

      if (!res.ok) {
        const errorText = await res.text();
        console.error("Resend API responded with error:", errorText);
        return createErrorResponse(
          "Failed to send request email via Resend",
          502,
        );
      }

      const resData = await res.json();
      console.log("Email sent successfully via Resend:", resData);

      return createResponse({ success: true, emailId: resData.id });
    } catch (error) {
      console.error("Error in request-voice-actor-page function:", error);
      return createErrorResponse(
        error instanceof Error ? error.message : "An unknown error occurred",
      );
    }
  }),
};
