name = "dubbingbase-website"
main = ".output/server/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "disable_nodejs_process_v2"] # disable_nodejs_process_v2: recommended for resvg-wasm/WASM on Workers

[assets]
directory = ".output/public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "340974572b504ed2aa20c160e18f5697"

[triggers]
# crons = ["* * * * *"]

[observability]
enabled = false
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = false
head_sampling_rate = 1
persist = false
invocation_logs = false

[observability.traces]
enabled = false
persist = false
head_sampling_rate = 1
